name: mycup_flutter
description: MyCup Application - A Flutter project.

publish_to: 'none' # Keeps it private

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grouped_list: ^6.0.0
  bitsdojo_window: ^0.1.6
  provider: ^6.1.2
  http: ^1.2.2
  logger: ^1.1.0
  intl: ^0.20.1
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/MyCupLogo.png"

flutter:
  uses-material-design: true

  assets:
    - images/